// Realistic Government Roads & Buildings (R&B) Infrastructure Assets Demo Dataset

const sampleInfrastructureAssets = [
  {
    assetId: 'R&B-ROAD-001',
    assetName: 'Ahmedabad-Gandhinagar Arterial Road Corridor',
    assetType: 'Road',
    description: 'Six-lane primary state highway corridor connecting Ahmedabad to the Capital complex in Gandhinagar.',
    district: 'Ahmedabad',
    taluka: 'Daskroi',
    location: 'S.G. Highway to Infocity Junction',
    address: 'Koba Circle to CH-0, Gandhinagar Highway',
    latitude: 23.1147,
    longitude: 72.5852,
    status: 'Active',
    condition: 'Good',
    ownership: 'Government of Gujarat - R&B Dept',
    constructionYear: 2019,
    lastInspectionDate: new Date('2026-08-15'),
    lastMaintenanceDate: new Date('2026-05-10'),
    estimatedCost: 125000000, // 12.5 Crores
    roadLength: 24.5,
    roadWidth: 22.0,
    surfaceType: 'Bituminous (Dense Bituminous Macadam)',
  },
  {
    assetId: 'R&B-BRG-002',
    assetName: 'Sabarmati River Major Bridge',
    assetType: 'Bridge',
    description: 'High-level multi-span pre-stressed concrete girder bridge across the Sabarmati River.',
    district: 'Ahmedabad',
    taluka: 'Sabarmati',
    location: 'Subhash Bridge Section, Riverfront Corridor',
    address: 'Across Sabarmati River connecting East & West R&B Circles',
    latitude: 23.0612,
    longitude: 72.5834,
    status: 'Active',
    condition: 'Fair',
    ownership: 'Government',
    constructionYear: 2014,
    lastInspectionDate: new Date('2026-09-02'),
    lastMaintenanceDate: new Date('2025-11-20'),
    estimatedCost: 85000000,
    bridgeLength: 480.0,
    bridgeWidth: 16.5,
    bridgeType: 'Pre-stressed Concrete (PSC) Box Girder',
  },
  {
    assetId: 'R&B-FLY-003',
    assetName: 'S.G. Highway Multi-Tier Flyover',
    assetType: 'Flyover',
    description: 'Four-lane elevated corridor designed to decongest high-density inter-district vehicular movement.',
    district: 'Ahmedabad',
    taluka: 'Ghatlodiya',
    location: 'Pakwan Crossroads & Thaltej Junction',
    address: 'Sarkhej - Gandhinagar Highway',
    latitude: 23.0538,
    longitude: 72.5098,
    status: 'Active',
    condition: 'Good',
    ownership: 'Government',
    constructionYear: 2021,
    lastInspectionDate: new Date('2026-07-20'),
    lastMaintenanceDate: new Date('2026-03-15'),
    estimatedCost: 142000000,
    flyoverLength: 1350.0,
    numberOfLanes: 4,
  },
  {
    assetId: 'R&B-BLD-004',
    assetName: 'District Administrative Headquarters Complex',
    assetType: 'Government Building',
    description: 'Multi-storey composite administrative building accommodating District Collectorate and divisional offices.',
    district: 'Gandhinagar',
    taluka: 'Gandhinagar',
    location: 'Sector 10 - Administrative Zone',
    address: 'Near Mahatma Mandir, Sector 10-A, Gandhinagar',
    latitude: 23.2156,
    longitude: 72.6369,
    status: 'Active',
    condition: 'Excellent',
    ownership: 'Government of Gujarat - R&B Dept',
    constructionYear: 2022,
    lastInspectionDate: new Date('2026-08-30'),
    lastMaintenanceDate: new Date('2026-06-12'),
    estimatedCost: 320000000,
    builtUpArea: 18500.0,
    numberOfFloors: 8,
  },
  {
    assetId: 'R&B-CUL-005',
    assetName: 'Nadiad-Vaso Rural Drainage Box Culvert',
    assetType: 'Culvert',
    description: 'Twin-cell RCC box culvert facilitating flood monsoon discharge under the rural Major District Road (MDR).',
    district: 'Kheda',
    taluka: 'Nadiad',
    location: 'KM 14/2 on Nadiad-Vaso Road',
    address: 'Rural Highway Chainage 14+200',
    latitude: 22.6841,
    longitude: 72.8421,
    status: 'Under Maintenance',
    condition: 'Poor',
    ownership: 'Government',
    constructionYear: 2011,
    lastInspectionDate: new Date('2026-09-10'),
    lastMaintenanceDate: new Date('2026-09-15'),
    estimatedCost: 3800000,
    roadLength: 0.05,
    roadWidth: 7.5,
    surfaceType: 'Concrete Slab',
  },
  {
    assetId: 'R&B-ROAD-006',
    assetName: 'Surat Ring Road Extension Package-2',
    assetType: 'Road',
    description: 'Heavy vehicle bypass corridor constructed with concrete pavement to connect industrial clusters to the expressway.',
    district: 'Surat',
    taluka: 'Choryasi',
    location: 'Sachin-Kamrej Industrial Peripheral',
    address: 'Outer Ring Road, South Surat Zone',
    latitude: 21.1702,
    longitude: 72.8311,
    status: 'Active',
    condition: 'Excellent',
    ownership: 'Government',
    constructionYear: 2023,
    lastInspectionDate: new Date('2026-08-10'),
    lastMaintenanceDate: new Date('2026-04-18'),
    estimatedCost: 210000000,
    roadLength: 32.4,
    roadWidth: 24.0,
    surfaceType: 'Rigid Concrete Pavement (PQC)',
  },
  {
    assetId: 'R&B-BRG-007',
    assetName: 'Narmada River Cable-Stayed Bridge Link',
    assetType: 'Bridge',
    description: 'Landmark cable-stayed bridge spanning the Narmada River, supporting inter-state coastal corridor traffic.',
    district: 'Bharuch',
    taluka: 'Bharuch',
    location: 'Golden Bridge Parallel Corridor',
    address: 'NH-8 / SH-6 Link Crossing, Bharuch',
    latitude: 21.7051,
    longitude: 72.9959,
    status: 'Active',
    condition: 'Good',
    ownership: 'Government',
    constructionYear: 2020,
    lastInspectionDate: new Date('2026-06-25'),
    lastMaintenanceDate: new Date('2026-01-14'),
    estimatedCost: 380000000,
    bridgeLength: 1344.0,
    bridgeWidth: 22.5,
    bridgeType: 'Cable-Stayed & Continuous Steel Girder',
  },
  {
    assetId: 'R&B-BLD-008',
    assetName: 'Vadodara Divisional R&B Engineering Circle Office',
    assetType: 'Government Office',
    description: 'Central engineering and quality control laboratory office building for the R&B Vadodara circle.',
    district: 'Vadodara',
    taluka: 'Vadodara Urban',
    location: 'Kothi Compound - Revenue Enclave',
    address: 'Kothi, Raopura, Vadodara - 390001',
    latitude: 22.3072,
    longitude: 73.1812,
    status: 'Active',
    condition: 'Fair',
    ownership: 'Government of Gujarat - R&B Dept',
    constructionYear: 2008,
    lastInspectionDate: new Date('2026-07-14'),
    lastMaintenanceDate: new Date('2025-08-10'),
    estimatedCost: 45000000,
    builtUpArea: 6400.0,
    numberOfFloors: 4,
  },
  {
    assetId: 'R&B-ROAD-009',
    assetName: 'Rajkot-Morbi Ceramic Industrial Highway',
    assetType: 'Road',
    description: 'High-axle-load heavy freight corridor connecting industrial manufacturing parks.',
    district: 'Rajkot',
    taluka: 'Paddhari',
    location: 'Rajkot North Bypass to Morbi Border',
    address: 'SH-24 Industrial Section',
    latitude: 22.4112,
    longitude: 70.7812,
    status: 'Under Maintenance',
    condition: 'Poor',
    ownership: 'Government',
    constructionYear: 2016,
    lastInspectionDate: new Date('2026-09-05'),
    lastMaintenanceDate: new Date('2026-09-18'),
    estimatedCost: 165000000,
    roadLength: 42.0,
    roadWidth: 14.0,
    surfaceType: 'Bituminous with Heavy Rutting Repair',
  },
  {
    assetId: 'R&B-BRG-010',
    assetName: 'Aji River Old Arch Heritage Bridge',
    assetType: 'Bridge',
    description: 'Historic stone masonry multi-arch bridge with modern structural retrofitting; weight restrictions enforced.',
    district: 'Rajkot',
    taluka: 'Rajkot Urban',
    location: 'Old City Connecting Causeway',
    address: 'Aji River Bed Road, Rajkot',
    latitude: 22.2812,
    longitude: 70.8142,
    status: 'Active',
    condition: 'Critical',
    ownership: 'Government',
    constructionYear: 1968,
    lastInspectionDate: new Date('2026-09-22'),
    lastMaintenanceDate: new Date('2025-04-12'),
    estimatedCost: 28000000,
    bridgeLength: 210.0,
    bridgeWidth: 9.5,
    bridgeType: 'Stone Masonry Arch with Sub-structure Retrofit',
  },
  {
    assetId: 'R&B-FLY-011',
    assetName: 'Vadodara Akota-Dandiya Bazar Elevated Corridor',
    assetType: 'Flyover',
    description: 'Iconic inner-city flyover spanning across railway tracks and congested municipal junctions.',
    district: 'Vadodara',
    taluka: 'Akota',
    location: 'Akota to Dandiya Bazar',
    address: 'Central Vadodara Urban Corridor',
    latitude: 22.2965,
    longitude: 73.1895,
    status: 'Active',
    condition: 'Good',
    ownership: 'Government',
    constructionYear: 2017,
    lastInspectionDate: new Date('2026-06-18'),
    lastMaintenanceDate: new Date('2026-02-10'),
    estimatedCost: 98000000,
    flyoverLength: 1820.0,
    numberOfLanes: 4,
  },
  {
    assetId: 'R&B-ROAD-012',
    assetName: 'Bhavnagar Coastal Highway Section',
    assetType: 'Road',
    description: 'Scenic and commercial coastal highway section providing heavy transport access to maritime ports.',
    district: 'Bhavnagar',
    taluka: 'Ghogha',
    location: 'Bhavnagar Old Port to Ghogha Terminal',
    address: 'State Coastal Highway Link',
    latitude: 21.7214,
    longitude: 72.2341,
    status: 'Under Construction',
    condition: 'Good',
    ownership: 'Government',
    constructionYear: 2026,
    lastInspectionDate: new Date('2026-08-28'),
    lastMaintenanceDate: null,
    estimatedCost: 195000000,
    roadLength: 19.8,
    roadWidth: 15.0,
    surfaceType: 'Dense Asphalt Concrete Under Construction',
  },
  {
    assetId: 'R&B-BLD-013',
    assetName: 'Patan Regional Polytechnic Institutional Campus',
    assetType: 'Government Building',
    description: 'Educational classroom blocks, laboratory wings, and administrative building constructed by R&B.',
    district: 'Patan',
    taluka: 'Patan',
    location: 'University Road Educational Hub',
    address: 'R&B Institutional Zone, Patan',
    latitude: 23.8493,
    longitude: 72.1266,
    status: 'Active',
    condition: 'Good',
    ownership: 'Government',
    constructionYear: 2018,
    lastInspectionDate: new Date('2026-05-19'),
    lastMaintenanceDate: new Date('2025-10-04'),
    estimatedCost: 89000000,
    builtUpArea: 14200.0,
    numberOfFloors: 3,
  },
  {
    assetId: 'R&B-CUL-014',
    assetName: 'Mehsana Canal Syphon Crossing Culvert',
    assetType: 'Culvert',
    description: 'Heavy-duty agricultural canal crossing pipe culvert under the state highway.',
    district: 'Mehsana',
    taluka: 'Kadi',
    location: 'SH-41 Chainage 38+450',
    address: 'Kadi-Chhatral Highway Cross Drain',
    latitude: 23.2982,
    longitude: 72.3312,
    status: 'Active',
    condition: 'Fair',
    ownership: 'Government',
    constructionYear: 2015,
    lastInspectionDate: new Date('2026-07-08'),
    lastMaintenanceDate: new Date('2025-06-15'),
    estimatedCost: 2600000,
    roadLength: 0.03,
    roadWidth: 12.0,
    surfaceType: 'Precast RCC Pipe Culvert',
  },
  {
    assetId: 'R&B-BRG-015',
    assetName: 'Kutch Coastal Tidal Creek Bridge',
    assetType: 'Bridge',
    description: 'High-salinity corrosion-resistant reinforced concrete bridge across marshy tidal inlets.',
    district: 'Kutch',
    taluka: 'Mandvi',
    location: 'Mandvi Coastal Bypass',
    address: 'Rukmavati River Estuary Link',
    latitude: 22.8341,
    longitude: 69.3481,
    status: 'Active',
    condition: 'Poor',
    ownership: 'Government',
    constructionYear: 2010,
    lastInspectionDate: new Date('2026-09-12'),
    lastMaintenanceDate: new Date('2024-12-05'),
    estimatedCost: 52000000,
    bridgeLength: 320.0,
    bridgeWidth: 11.0,
    bridgeType: 'RCC T-Beam with Epoxy Coated Rebars',
  },
  {
    assetId: 'R&B-INF-016',
    assetName: 'Junagadh District Inspection Bungalow (IB)',
    assetType: 'Other Infrastructure',
    description: 'Government VIP transit rest house and administrative meeting retreat maintained by the R&B Special Sub-Division.',
    district: 'Junagadh',
    taluka: 'Junagadh City',
    location: 'Girnar Foothills Sanctuary Road',
    address: 'Bhavnath Taleti Road, Junagadh',
    latitude: 21.5222,
    longitude: 70.4579,
    status: 'Retired',
    condition: 'Critical',
    ownership: 'Government',
    constructionYear: 1952,
    lastInspectionDate: new Date('2026-04-10'),
    lastMaintenanceDate: new Date('2022-03-15'),
    estimatedCost: 15000000,
    builtUpArea: 2800.0,
    numberOfFloors: 1,
  },
];

// Sample Inspections data generator
const sampleInspections = [
  {
    assetRefId: 'R&B-ROAD-001',
    inspectionDate: new Date('2026-08-15'),
    inspectorName: 'Er. Rajesh Patel (Executive Engineer, R&B)',
    condition: 'Good',
    remarks: 'Routine pre-monsoon road safety and roughness index evaluation. Pavement texture and lane markings intact.',
    recommendation: 'Scheduled routine shoulder cleaning and storm drain unblocking before monsoon onset.',
  },
  {
    assetRefId: 'R&B-BRG-002',
    inspectionDate: new Date('2026-09-02'),
    inspectorName: 'Er. Amit Shah (Superintending Engineer, Bridge Cell)',
    condition: 'Fair',
    remarks: 'Sub-structure scour checked. Minor hairline cracks observed on pier cap #4 and expansion joints show wear.',
    recommendation: 'Recommend non-destructive rebound hammer testing and expansion joint elastomeric pad replacement.',
  },
  {
    assetRefId: 'R&B-CUL-005',
    inspectionDate: new Date('2026-09-10'),
    inspectorName: 'Er. Harish Solanki (Assistant Engineer)',
    condition: 'Poor',
    remarks: 'Severe silt accumulation choking 60% of barrel area. Upstream wing wall shows structural spalling.',
    recommendation: 'Immediate desilting and structural apron reconstruction required before further scour occurs.',
  },
  {
    assetRefId: 'R&B-ROAD-009',
    inspectionDate: new Date('2026-09-05'),
    inspectorName: 'Er. N. V. Dave (R&B Quality Control Inspector)',
    condition: 'Poor',
    remarks: 'Heavy commercial ceramic freight vehicles caused significant wheel path rutting (depth > 25mm) and fatigue cracking.',
    recommendation: 'Milling of damaged surface course and overlay with Polymer Modified Bitumen (PMB-40).',
  },
  {
    assetRefId: 'R&B-BRG-010',
    inspectionDate: new Date('2026-09-22'),
    inspectorName: 'Dr. K. S. Joshi (Structural Forensic Consultant)',
    condition: 'Critical',
    remarks: 'Critical displacement noted in arch keystone #2. Severe mortar degradation. Heavy vibrations under load.',
    recommendation: 'Urgent traffic load restriction to light passenger vehicles only. Comprehensive retrofitting tender recommended.',
  },
  {
    assetRefId: 'R&B-BLD-004',
    inspectionDate: new Date('2026-08-30'),
    inspectorName: 'Er. Meera Trivedi (R&B Electrical & Structural Cell)',
    condition: 'Excellent',
    remarks: 'Annual building integrity and fire safety audit. Structural frame, HVAC plant, and emergency exits in prime condition.',
    recommendation: 'No structural interventions required. Routine filter maintenance scheduled.',
  },
];

// Sample Maintenance data generator
const sampleMaintenance = [
  {
    assetRefId: 'R&B-ROAD-001',
    maintenanceDate: new Date('2026-05-10'),
    maintenanceType: 'Preventive Road Resurfacing & Crack Sealing',
    description: 'Application of micro-surfacing emulsion and thermo-plastic road marking along 12km stretch.',
    status: 'Completed',
    estimatedCost: 8500000,
    actualCost: 8250000,
    contractor: 'Gujarat State Infra Projects Ltd.',
    completionDate: new Date('2026-05-28'),
    remarks: 'Work executed ahead of schedule with certified quality clearance.',
  },
  {
    assetRefId: 'R&B-CUL-005',
    maintenanceDate: new Date('2026-09-15'),
    maintenanceType: 'Culvert Desilting & Wing Wall Restoration',
    description: 'Emergency hydraulic clearing, boulder pitching of embankment, and concrete repair of wing walls.',
    status: 'In Progress',
    estimatedCost: 1200000,
    actualCost: 0,
    contractor: 'M/s Patel Rural Infrastructure',
    completionDate: null,
    remarks: '50% desilting achieved. Awaiting specialized underwater epoxy grouting materials.',
  },
  {
    assetRefId: 'R&B-ROAD-009',
    maintenanceDate: new Date('2026-09-18'),
    maintenanceType: 'Heavy Pavement Milling & Bituminous Overlay',
    description: 'Cold milling of 50mm rutted surface layer followed by 50mm Bituminous Concrete overlay with tack coat.',
    status: 'In Progress',
    estimatedCost: 34000000,
    actualCost: 0,
    contractor: 'Shreeji Roadways & Highways Construction',
    completionDate: null,
    remarks: 'Night-time lane closure implemented to manage heavy ceramic truck movement.',
  },
  {
    assetRefId: 'R&B-BRG-002',
    maintenanceDate: new Date('2026-10-15'),
    maintenanceType: 'Expansion Joint Replacement & Pier Grouting',
    description: 'Replacement of damaged strip seal expansion joints and epoxy injection into pier cap micro-cracks.',
    status: 'Planned',
    estimatedCost: 4500000,
    actualCost: 0,
    contractor: 'Bridge Engineering Systems Corp.',
    completionDate: null,
    remarks: 'Tender awarded. Work scheduled to commence post-monsoon.',
  },
  {
    assetRefId: 'R&B-BRG-010',
    maintenanceDate: new Date('2026-10-01'),
    maintenanceType: 'Emergency Arch Underpinning & Structural Jacket',
    description: 'Installation of temporary steel shoring towers followed by reinforced shotcreting of arch soffit.',
    status: 'Planned',
    estimatedCost: 9200000,
    actualCost: 0,
    contractor: 'Heritage Infrastructure Restorations',
    completionDate: null,
    remarks: 'Structural engineering clearance granted. Barricades installed.',
  },
];

// Sample Lifecycle Audit Trail / History data generator
const sampleLifecycleEvents = [
  {
    assetRefId: 'R&B-ROAD-001',
    action: 'Asset Registered',
    previousValue: '',
    newValue: 'Active',
    description: 'Initial registration of Ahmedabad-Gandhinagar Arterial Road Corridor in R&B Central Database upon handover.',
    performedBy: 'System User (Admin Officer)',
    createdAt: new Date('2019-11-20'),
  },
  {
    assetRefId: 'R&B-ROAD-001',
    action: 'Inspection Added',
    previousValue: 'Excellent',
    newValue: 'Good',
    description: 'Annual monsoon inspection conducted by Er. Rajesh Patel. Condition documented as Good.',
    performedBy: 'Er. Rajesh Patel',
    createdAt: new Date('2026-08-15'),
  },
  {
    assetRefId: 'R&B-CUL-005',
    action: 'Asset Registered',
    previousValue: '',
    newValue: 'Active',
    description: 'Rural culvert asset recorded under District Road Asset Register.',
    performedBy: 'System User (Admin Officer)',
    createdAt: new Date('2011-06-15'),
  },
  {
    assetRefId: 'R&B-CUL-005',
    action: 'Condition Changed',
    previousValue: 'Fair',
    newValue: 'Poor',
    description: 'Post-flood field audit identified severe silting and wing wall damage. Condition downgraded to Poor.',
    performedBy: 'Er. Harish Solanki',
    createdAt: new Date('2026-09-10'),
  },
  {
    assetRefId: 'R&B-CUL-005',
    action: 'Maintenance Started',
    previousValue: 'Active',
    newValue: 'Under Maintenance',
    description: 'Emergency Desilting & Wing Wall Restoration initiated. Asset status transitioned to Under Maintenance.',
    performedBy: 'R&B Works Division',
    createdAt: new Date('2026-09-15'),
  },
  {
    assetRefId: 'R&B-ROAD-009',
    action: 'Condition Changed',
    previousValue: 'Fair',
    newValue: 'Poor',
    description: 'Heavy rutting documented during high-axle load audit. Immediate resurfacing mandated.',
    performedBy: 'Er. N. V. Dave',
    createdAt: new Date('2026-09-05'),
  },
  {
    assetRefId: 'R&B-ROAD-009',
    action: 'Maintenance Started',
    previousValue: 'Active',
    newValue: 'Under Maintenance',
    description: 'Pavement Milling & Bituminous Overlay commenced by contractor. Asset marked Under Maintenance.',
    performedBy: 'R&B Works Division',
    createdAt: new Date('2026-09-18'),
  },
  {
    assetRefId: 'R&B-BRG-010',
    action: 'Condition Changed',
    previousValue: 'Poor',
    newValue: 'Critical',
    description: 'Structural inspection reported arch displacement. Condition updated to Critical. Load restriction enforced.',
    performedBy: 'Dr. K. S. Joshi',
    createdAt: new Date('2026-09-22'),
  },
];

module.exports = {
  sampleInfrastructureAssets,
  sampleInspections,
  sampleMaintenance,
  sampleLifecycleEvents,
};
